TOPLEVEL_LANG = verilog

VERILOG_SOURCES = ../../07-bus/02_serial_1bit_adder/serial_1bit_adder.sv

TOPLEVEL = serial_1bit_adder
COCOTB_TEST_MODULES = serial_adder_test

include $(shell cocotb-config --makefiles)/Makefile.sim
