TOPLEVEL_LANG = verilog

VERILOG_SOURCES = ../../07-bus/01_merge_parallel/merge_parallel.sv

TOPLEVEL = merge_parallel
COCOTB_TEST_MODULES = merge_parallel_test

include $(shell cocotb-config --makefiles)/Makefile.sim
