name: build and run testbenches

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hdl/iverilog:latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - name: Install make
        run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends make
      - name: Build and start testbenches
        run: |
          find src -type f -name build_and_test_all.sh -execdir '{}' '+'
